import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually defined sidebar with logical section boundaries
  tutorialSidebar: [
    'intro',
    'installation',

    // Getting Started Section
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },

    // Dream Framework Section
    {
      type: 'category',
      label: 'Dream (Models & ORM)',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'models' }],
    },

    // Psychic Framework Section
    {
      type: 'category',
      label: 'Controllers',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'controllers' }],
    },

    {
      type: 'category',
      label: 'Routing',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'routing' }],
    },

    {
      type: 'category',
      label: 'Serializers',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'serializers' }],
    },

    // Configuration & CLI Section
    {
      type: 'category',
      label: 'Configuration',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'config' }],
    },

    {
      type: 'category',
      label: 'CLI Tools',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'cli' }],
    },

    // Advanced Features Section
    {
      type: 'category',
      label: 'Decorators',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'decorators' }],
    },

    {
      type: 'category',
      label: 'OpenAPI',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'openapi' }],
    },

    {
      type: 'category',
      label: 'Testing',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'specs' }],
    },

    {
      type: 'category',
      label: 'Plugins',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'plugins' }],
    },

    {
      type: 'category',
      label: 'Utilities',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'utils' }],
    },

    // Deployment & Production Section
    {
      type: 'category',
      label: 'Deployment',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'deployment' }],
    },

    // Development & Contributing Section
    {
      type: 'category',
      label: 'Editor Setup',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'editors' }],
    },

    {
      type: 'category',
      label: 'Contributing',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'contributing' }],
    },

    {
      type: 'category',
      label: 'Learn More',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'learn-more' }],
    },
  ],

  // Keep the guides sidebar as-is for now
  guides: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
